import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

/**
 * Generate a PDF report buffer from structured report data.
 * @param {object} reportData - from reportGenerator.buildReportData()
 * @returns {Buffer} PDF binary
 */
export async function generatePDF(reportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Cover page ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(30, 58, 138); // dark blue
  doc.text('DPDP Compliance Report', pageWidth / 2, 60, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Website: ${reportData.url}`, pageWidth / 2, 80, { align: 'center' });
  doc.text(`Generated: ${new Date(reportData.generatedAt).toLocaleDateString('en-IN')}`, pageWidth / 2, 90, { align: 'center' });

  // Score circle
  doc.setFontSize(60);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(37, 99, 235);
  doc.text(`${reportData.overallScore}`, pageWidth / 2, 130, { align: 'center' });
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text('Compliance Score', pageWidth / 2, 145, { align: 'center' });

  // --- Executive Summary (new page) ---
  doc.addPage();
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 138);
  doc.text('Executive Summary', 20, 30);
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const summaryLines = doc.splitTextToSize(reportData.executiveSummary, pageWidth - 40);
  doc.text(summaryLines, 20, 45);

  // --- Findings table ---
  doc.addPage();
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 138);
  doc.text('Detailed Findings', 20, 30);
  const tableBody = reportData.findings.map(f => [
    f.check,
    f.status === 'passed' ? 'PASSED' : 'FAILED',
    f.severity.toUpperCase(),
    f.fix || '',
  ]);
  doc.autoTable({
    head: [['Check', 'Status', 'Severity', 'Recommended Fix']],
    body: tableBody,
    startY: 45,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [37, 99, 235], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 'auto' },
    },
  });

  // --- Action Plan ---
  const finalY = doc.lastAutoTable.finalY + 15;
  if (finalY > 240) doc.addPage();
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 138);
  doc.text('Recommended Action Plan', 20, finalY);
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  let y = finalY + 12;
  reportData.actions.forEach((action, i) => {
    const text = `${i + 1}. ${action}`;
    const lines = doc.splitTextToSize(text, pageWidth - 40);
    doc.text(lines, 20, y);
    y += lines.length * 6 + 4;
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by DPDPready – Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Return as Buffer
  const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
  return pdfBuffer;
}
